/* Display */
#define CLOCK 148500 /* kHz */
#define XPIX 540
#define YPIX 2560
#define XBLANK 588
#define XOFFSET 522
#define XPULSE 10
#define YBLANK 73
#define YOFFSET 42
#define YPULSE 10
#define DPI 518
#define VFREQ 50 /* Hz */
#define TIMING_NAME "RV059FBB"
/* No ESTABLISHED_TIMINGx_BITS */
#define HSYNC_POL 0
#define VSYNC_POL 0
#define XSIZE 81

/* Manufacturer */
#define MFG_LNX1 'L'
#define MFG_LNX2 'Z'
#define MFG_LNX3 'T'
#define SERIAL 0
#define YEAR 2017
#define WEEK 12

#include "edid.h"
