#!/usr/bin/sh
set -e

# get printer model
MODEL_PATH=/etc/sl1fw/model
if [ ! -d "$MODEL_PATH" ] || [ -z `ls $MODEL_PATH` ]; then
        echo "Unknown printer model"
        exit 1
else
        PRINTER_MODEL=`ls $MODEL_PATH`
fi

# get auth method
cd /etc/nginx/sites-enabled
/usr/bin/rm -rf *
if [ -f "/etc/nginx/http_digest_enabled" ]; then
        HTTP_DIGEST=""
else
        HTTP_DIGEST="auth_digest off;"
fi

# edit template file and make the site enabled
cd /etc/nginx/sites-available
/usr/bin/sed "s/@DOCUMENT_ROOT@/\/srv\/http\/${PRINTER_MODEL}/g; s/@HTTP_DIGEST@/${HTTP_DIGEST}/g;" prusa-link.conf.template > prusa-link
/usr/bin/ln -s ../sites-available/prusa-link ../sites-enabled/prusa-link
/usr/sbin/nginx -t
