/* Display */
#define CLOCK 148500 /* kHz */
#define XPIX 540
#define YPIX 2560
#define XBLANK 409
#define XOFFSET 302
#define XPULSE 32
#define YBLANK 48
#define YOFFSET 28
#define YPULSE 10
#define DPI 518
#define VFREQ 60 /* Hz */
#define TIMING_NAME "RV059FBB"
/* No ESTABLISHED_TIMINGx_BITS */
#define HSYNC_POL 0
#define VSYNC_POL 0
#define XSIZE 81

/* Manufacturer */
#define MFG_LNX1 'L'
#define MFG_LNX2 'Z'
#define MFG_LNX3 'T'
#define SERIAL 0
#define YEAR 2017
#define WEEK 11

#include "edid.h"
